version: '3'
services:
    frontend:
        build:
            context: ../../.
            dockerfile: infra/frontend/Dockerfile.dev
        image: nudrop-frontend-dev
        environment:
            - NODE_ENV=development
        volumes: 
            - ./../../frontend:/usr/src/app
        ports:
            - '8080:8080'

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        network_mode: host
